version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://<user>:<password>@db:5432/<dbname>
      - JWT_SECRET_KEY=<your_jwt_secret_key>
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: <user>
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: <dbname>
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
