services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrations:
    build: .
    env_file:
      - .env
    command: alembic upgrade head
    depends_on:
      - db

volumes:
  postgres_data:
